name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src, llvm-tools-preview
    - name: Adding bootimage
      run: cargo install bootimage
    - name: Adding target 
      run: rustup target add x86_64-unknown-none
    - name: Build
      run: cargo build --target path/to/your/target.json
    - name: Run tests
      run: cargo test
