name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Adding dependency
      run : rustup component add llvm-tools-preview
    - name: rust-src
      run: rustup component add rust-src
    - name: Adding bootimage
      run: cargo install bootimage
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test 
